# Datenstrom Yellow extension settings

Extension: Markdown
Version: 0.9.10
Description: Text formatting for humans.
Developer: Anna Svensson
Tag: feature
DownloadUrl: https://github.com/annaesvensson/yellow-markdown/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/annaesvensson/yellow-markdown
DocumentationLanguage: en, de, sv
Published: 2026-09-24 00:22:20
Status: maintained
system/workers/markdown.php: markdown.php, create, update
